//
//  HomePresenter.swift
//  PlayCleanSwift
//
//  Created by Ari Supriatna on 04/09/19.
//  Copyright (c) 2019 Ari Supriatna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
  func presentFoods(response: Home.FetchFoods.Response)
}

class HomePresenter: HomePresentationLogic
{
  weak var viewController: HomeDisplayLogic?
  
  // MARK: Do something
  
  func presentFoods(response: Home.FetchFoods.Response)
  {
    let viewModel = Home.FetchFoods.ViewModel(displayedFoods: response.foods)
    viewController?.displayedFood(viewModel: viewModel)
  }
}
