//
//  HomeInteractor.swift
//  PlayCleanSwift
//
//  Created by Ari Supriatna on 04/09/19.
//  Copyright (c) 2019 Ari Supriatna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
  func doFetchFoods(request: Home.FetchFoods.Request)
}

protocol HomeDataStore
{
  //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
  var presenter: HomePresentationLogic?
  var worker: HomeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doFetchFoods(request: Home.FetchFoods.Request)
  {
    worker = HomeWorker()
    worker?.fetchFood(request: request, handler: { (foods) in
      let response = Home.FetchFoods.Response(foods: foods)
      
      self.presenter?.presentFoods(response: response)
    })
  }
}
