//
//  LoginWorker.swift
//  PlayCleanSwift
//
//  Created by Ari Supriatna on 04/09/19.
//  Copyright (c) 2019 Ari Supriatna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker {
  
  //MARK: Constant Account
  let usernameConstant = "ari"
  let passwordConstant = "123"
  
//  func fetchLogin(username: String?, password: String?) -> Login.FetchLogin.Response {
//    if username == usernameConstant && password == passwordConstant {
//      let response = Login.FetchLogin.Response(successLogin: true, errorLogin: false, username: usernameConstant)
//      return response
//    }
//    let response = Login.FetchLogin.Response(successLogin: false, errorLogin: true, username: usernameConstant)
//    return response
//  }
  
  func fetchLogin(request: Login.FetchLogin.Request, completionHandler: @escaping(LoginModel) -> Void) {
    if request.username == usernameConstant && request.password == passwordConstant {
      let responseData = LoginModel(successLogin: true, errorLogin: false, username: request.username)
      completionHandler(responseData)
    } else {
      let responseError = LoginModel(successLogin: false, errorLogin: true, username: "")
      completionHandler(responseError)
    }
  }
}
