//
//  LoginPresenter.swift
//  PlayCleanSwift
//
//  Created by Ari Supriatna on 04/09/19.
//  Copyright (c) 2019 Ari Supriatna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
  func presentLogin(response: Login.FetchLogin.Response)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
  
  func presentLogin(response: Login.FetchLogin.Response)
  {
//    let viewModel = Login.FetchLogin.ViewModel(successLogin: response.successLogin, errorLogin: response.errorLogin, username: response.username)
//    viewController?.displayLogin(viewModel: viewModel)
    let viewModel = Login.FetchLogin.ViewModel(dataViewModel: response.data)
    viewController?.displayLogin(viewModel: viewModel)
  }
}
