//
//  LoginModels.swift
//  PlayCleanSwift
//
//  Created by Ari Supriatna on 04/09/19.
//  Copyright (c) 2019 Ari Supriatna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct LoginModel {
  var successLogin: Bool
  var errorLogin: Bool
  var username: String
}

enum Login
{
  // MARK: Use cases
  
  enum FetchLogin
  {
    struct Request
    {
      var username: String
      var password: String
    }
    struct Response
    {
      var data: LoginModel
    }
    struct ViewModel
    {
      var dataViewModel: LoginModel
    }
  }
}
