//
//  LoginInteractor.swift
//  PlayCleanSwift
//
//  Created by Ari Supriatna on 04/09/19.
//  Copyright (c) 2019 Ari Supriatna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
  func login(request: Login.FetchLogin.Request)
}

protocol LoginDataStore
{
  //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
  var presenter: LoginPresentationLogic?
  var worker: LoginWorker?
  
  // MARK: Login
  
  func login(request: Login.FetchLogin.Request)
  {
    worker = LoginWorker()
    
    //MARK: 3
    worker?.fetchLogin(request: request, completionHandler: { (loginModel) in
      
      if loginModel.successLogin {
        let response = Login.FetchLogin.Response(data: loginModel)
        self.presenter?.presentLogin(response: response)
      } else {
        let responseError = Login.FetchLogin.Response(data: loginModel)
        self.presenter?.presentLogin(response: responseError)
      }
      
    })
    
    
    //MARK: 2
//    let fetchLogin = worker?.fetchLogin(username: request.username, password: request.password)
//
//    if fetchLogin!.successLogin {
//      presenter?.presentLogin(response: Login.FetchLogin.Response(successLogin: fetchLogin!.successLogin, errorLogin: fetchLogin!.errorLogin, username: fetchLogin!.username))
//    } else {
//      presenter?.presentLogin(response: Login.FetchLogin.Response(successLogin: fetchLogin!.successLogin, errorLogin: fetchLogin!.errorLogin, username: fetchLogin!.username))
//    }

    //MARK: 1
//    if (worker?.fetchLogin(username: request.username, password: request.password))! {
//      let response = Login.FetchLogin.Response(successLogin: true, errorLogin: false, username: request.username)
//      presenter?.presentLogin(response: response)
//    } else {
//      let response = Login.FetchLogin.Response(successLogin: false, errorLogin: true, username: request.username)
//      presenter?.presentLogin(response: response)
//    }
  }
}
