//
//  FoodDetailInteractor.swift
//  PlayCleanSwift
//
//  Created by Ari Supriatna on 05/09/19.
//  Copyright (c) 2019 Ari Supriatna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FoodDetailBusinessLogic
{
  func doSomething(request: FoodDetail.Something.Request)
}

protocol FoodDetailDataStore
{
  //var name: String { get set }
}

class FoodDetailInteractor: FoodDetailBusinessLogic, FoodDetailDataStore
{
  var presenter: FoodDetailPresentationLogic?
  var worker: FoodDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: FoodDetail.Something.Request)
  {
    worker = FoodDetailWorker()
    worker?.doSomeWork()
    
    let response = FoodDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
