//
//  FoodDetailPresenter.swift
//  PlayCleanSwift
//
//  Created by Ari Supriatna on 05/09/19.
//  Copyright (c) 2019 Ari Supriatna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FoodDetailPresentationLogic
{
  func presentSomething(response: FoodDetail.Something.Response)
}

class FoodDetailPresenter: FoodDetailPresentationLogic
{
  weak var viewController: FoodDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: FoodDetail.Something.Response)
  {
    let viewModel = FoodDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
