//
//  SearchWorker.swift
//  PlayCleanSwift
//
//  Created by Ari Supriatna on 05/09/19.
//  Copyright (c) 2019 Ari Supriatna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import SwiftyJSON

class SearchWorker {
  let SEARCH_MEAL_URL = "https://www.themealdb.com/api/json/v1/1/search.php"
  
  func fetchSearchMeal(request: Search.FetchSearchMeal.Request, handler: @escaping(JSON) -> Void) {
    let params: [String: String] = ["s": request.name]
    
    Alamofire.request(SEARCH_MEAL_URL, method: .get, parameters: params).responseJSON { (response) in
      if response.result.isSuccess {
        let dataFoods: JSON = JSON(response.result.value!)
        let listMeals = dataFoods["meals"]
        
        print(listMeals)
        
        handler(listMeals)
      }
    }
  }
}
