//
//  SearchPresenter.swift
//  PlayCleanSwift
//
//  Created by Ari Supriatna on 05/09/19.
//  Copyright (c) 2019 Ari Supriatna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic
{
  func presentSearchMeal(response: Search.FetchSearchMeal.Response)
}

class SearchPresenter: SearchPresentationLogic
{
  weak var viewController: SearchDisplayLogic?
  
  // MARK: Do something
  
  func presentSearchMeal(response: Search.FetchSearchMeal.Response)
  {
    let viewModel = Search.FetchSearchMeal.ViewModel(displayedData: response.foods)
    viewController?.displaySearchMeal(viewModel: viewModel)
  }
}
