//
//  SearchModels.swift
//  PlayCleanSwift
//
//  Created by Ari Supriatna on 05/09/19.
//  Copyright (c) 2019 Ari Supriatna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftyJSON

enum Search {
  // MARK: Use cases
  
  enum FetchSearchMeal {
    struct Request {
      var name: String
    }
    
    struct Response {
      var foods: JSON
    }
    
    struct ViewModel {
      var displayedData: JSON
    }
  }
}
